// Velmora - 24 Products Catalog with exact images and pricing from Wix store
const products = [
  {
    id: "prod-1",
    slug: "be-kind-hoodie",
    name: "Be Kind Hoodie",
    category: "hoodies",
    categoryLabel: "Hoodies & Sweatshirts",
    price: 1999,
    originalPrice: 2499,
    rating: 4.9,
    reviewsCount: 48,
    badge: "Bestseller",
    image: "https://static.wixstatic.com/media/290a69_3c6b276a94cf4d23a2063a97ef6fb599~mv2.png",
    description: "Spread warmth with our premium heavyweight cotton fleece hoodie featuring custom typography 'Be Kind'. Tailored with a relaxed streetwear drop shoulder fit and double-layered warm hood.",
    seoKeywords: ["oversized hoodie men", "oversized hoodie women", "streetwear hoodies"],
    colors: ["#1e1e1e", "#e8e5dc", "#8a9a86"],
    colorNames: ["Washed Black", "Vintage Cream", "Sage Green"],
    sizes: ["S", "M", "L", "XL", "XXL"]
  },
  {
    id: "prod-2",
    slug: "ceramic-flower-vase",
    name: "Bold Blue Graphic Print T-Shirt",
    category: "t-shirts",
    categoryLabel: "T-Shirts",
    price: 270,
    originalPrice: 499,
    rating: 4.7,
    reviewsCount: 31,
    badge: "Trending",
    image: "https://static.wixstatic.com/media/290a69_76ab3727bf5d49178af1c7e57c846a80~mv2.png",
    description: "Ultra-comfy everyday boxy graphic tee crafted from 240 GSM pre-shrunk cotton. Vivid reactive print designed for long-lasting vibrant color after dozens of washes.",
    seoKeywords: ["graphic t shirts india", "graphic t shirts", "oversized t shirt for women"],
    colors: ["#2b3d5b", "#ffffff", "#121212"],
    colorNames: ["Cobalt Blue", "Pure White", "Jet Black"],
    sizes: ["XS", "S", "M", "L", "XL"]
  },
  {
    id: "prod-3",
    slug: "clock-it-t-shirt",
    name: "Clock It T-Shirt",
    category: "t-shirts",
    categoryLabel: "T-Shirts",
    price: 799,
    originalPrice: 999,
    rating: 4.8,
    reviewsCount: 64,
    badge: "Popular",
    image: "https://static.wixstatic.com/media/290a69_10c08e6752424516a7d666745754f375~mv2.png",
    description: "Statement minimalist streetwear graphic tee. Bold typography with high-density puff print detailing. Designed to elevate your everyday rotation effortlessly.",
    seoKeywords: ["oversized white t shirt", "graphic t shirts india", "t shirt graphic design"],
    colors: ["#ffffff", "#212121", "#d8d3c5"],
    colorNames: ["Off White", "Coal Black", "Bone"],
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: "prod-4",
    slug: "counting-my-lucky-stars-custom-photo-tote",
    name: "Counting My Lucky Stars Custom Photo Tote",
    category: "bags",
    categoryLabel: "Bags & Totes",
    price: 699,
    originalPrice: 899,
    rating: 5.0,
    reviewsCount: 29,
    badge: "Customizable",
    image: "https://static.wixstatic.com/media/290a69_0cdf7197ff22418db00d000875bc3c8e~mv2.jpeg",
    description: "Heavy-duty 14oz canvas tote bag with reinforced handles and flat base for structured carry. Perfect as a daily work, library, or aesthetic laptop tote.",
    seoKeywords: ["canvas tote bag", "office tote bag", "tote bag for office"],
    colors: ["#f2eee5", "#1f1f1f"],
    colorNames: ["Natural Canvas", "Midnight Black"],
    sizes: ["Standard (15x16 in)"]
  },
  {
    id: "prod-5",
    slug: "custom-film-strip-photo-phone-case",
    name: "Custom Film Strip Photo Phone Case",
    category: "accessories",
    categoryLabel: "Phone Cases & Accessories",
    price: 499,
    originalPrice: 699,
    rating: 4.9,
    reviewsCount: 52,
    badge: "Customizable",
    image: "https://static.wixstatic.com/media/290a69_a67c04450b034ba08cf11d7f649ac7ec~mv2.jpeg",
    description: "Nostalgic 35mm film strip print on dual-layer protective shockproof case. Raised bezels ensure edge-to-edge camera and screen safety with aesthetic gloss finish.",
    seoKeywords: ["aesthetic phone cases", "silicone phone case", "phone cases"],
    colors: ["#1c1c1c", "#f7f7f7", "#e4b4b4"],
    colorNames: ["Transparent Smoke", "Clear Gloss", "Rose Mist"],
    sizes: ["iPhone 13-16 Pro/Max", "Samsung S23/S24", "OnePlus 12/13"]
  },
  {
    id: "prod-6",
    slug: "custom-name-sketchbook",
    name: "Custom Name Sketchbook",
    category: "stationery",
    categoryLabel: "Stationery & Planners",
    price: 599,
    originalPrice: 799,
    rating: 4.8,
    reviewsCount: 19,
    badge: "Personalized",
    image: "https://static.wixstatic.com/media/290a69_4f3a6e83ed9b427f8919fbaafc7b99ac~mv2.png",
    description: "Hardcover Smyth-sewn binding sketchbook filled with 160 GSM bleed-proof ivory paper. Personalize your name or custom motto on the textured linen spine.",
    seoKeywords: ["daily planner diary", "aesthetic stationery", "custom notebook"],
    colors: ["#3b3a36", "#a69580", "#6b7a6d"],
    colorNames: ["Charcoal", "Warm Oatmeal", "Eucalyptus"],
    sizes: ["A5 (Hardbound)"]
  },
  {
    id: "prod-7",
    slug: "cute-things-to-remember-list-pad",
    name: "Cute Things To Remember List Pad",
    category: "stationery",
    categoryLabel: "Stationery & Planners",
    price: 249,
    originalPrice: 349,
    rating: 4.9,
    reviewsCount: 88,
    badge: "Best Value",
    image: "https://static.wixstatic.com/media/290a69_1a50a18f4c354ef5a661fcb74da4dea1~mv2.png",
    description: "50 tear-off sheets with dreamy pastel checklist layout. Premium 100 GSM uncoated wood-free paper that never bleeds through gel pens, markers, or fountain inks.",
    seoKeywords: ["to do list", "daily planner diary", "stationery notes"],
    colors: ["#fed7d7", "#feebc8", "#c6f6d5"],
    colorNames: ["Pastel Blossom", "Honey Cream", "Mint Whisper"],
    sizes: ["50 Sheets (4x7 in)"]
  },
  {
    id: "prod-8",
    slug: "fast-feels-forever-racing-t-shirt",
    name: "Fast Feels Forever Racing T-Shirt",
    category: "t-shirts",
    categoryLabel: "T-Shirts",
    price: 999,
    originalPrice: 1299,
    rating: 4.9,
    reviewsCount: 42,
    badge: "Streetwear",
    image: "https://static.wixstatic.com/media/290a69_80170c9a8d99442d8a7e07300d6e1b1d~mv2.png",
    description: "High-octane motorsport graphic oversized t-shirt. Features back-and-chest vintage racing typography print on 100% combed cotton jersey with thick ribbed collar.",
    seoKeywords: ["oversized white t shirt", "graphic t shirts india", "streetwear outfits"],
    colors: ["#111111", "#ffffff", "#b91c1c"],
    colorNames: ["Pitch Black", "Racing White", "Track Red"],
    sizes: ["S", "M", "L", "XL", "XXL"]
  },
  {
    id: "prod-9",
    slug: "gemini-personalized-graphic-phone-case",
    name: "Gemini Personalized Graphic Phone Case",
    category: "accessories",
    categoryLabel: "Phone Cases & Accessories",
    price: 449,
    originalPrice: 599,
    rating: 4.7,
    reviewsCount: 23,
    badge: "Zodiac Series",
    image: "https://static.wixstatic.com/media/290a69_f87f4bb08c0d480c98b8ba678a0d6d28~mv2.png",
    description: "Intricate astrological constellation design on matte finish polycarbonate shell. Ultra-slim profile with anti-scratch coating and responsive tactile tactile button covers.",
    seoKeywords: ["aesthetic phone cases", "silicone phone case", "phone case stickers"],
    colors: ["#18181b", "#312e81"],
    colorNames: ["Cosmic Onyx", "Deep Indigo"],
    sizes: ["All iPhone & Pixel Models"]
  },
  {
    id: "prod-10",
    slug: "hot-girls-who-overthink-t-shirt",
    name: "Hot Girls Who Overthink T-Shirt",
    category: "t-shirts",
    categoryLabel: "T-Shirts",
    price: 599,
    originalPrice: 899,
    rating: 5.0,
    reviewsCount: 114,
    badge: "Viral Hit",
    image: "https://static.wixstatic.com/media/290a69_b30dae2ed0ad4657bd94f116f097aa24~mv2.jpeg",
    description: "The viral cultural staple tee. Soft vintage washed aesthetic, relaxed boxy silhouette, and bold front witty slogan. Pairs flawlessly with parachute pants and denim.",
    seoKeywords: ["oversized t shirt for women", "women's graphic t shirts", "oversized t shirt women"],
    colors: ["#faf7f2", "#1f1f1f", "#e6cfcf"],
    colorNames: ["Vintage Off-White", "Washed Charcoal", "Dusty Pink"],
    sizes: ["XS", "S", "M", "L", "XL"]
  },
  {
    id: "prod-11",
    slug: "i-carry-intense-emotions-sweatshirt",
    name: "I Carry Intense Emotions Sweatshirt",
    category: "hoodies",
    categoryLabel: "Hoodies & Sweatshirts",
    price: 1299,
    originalPrice: 1799,
    rating: 4.8,
    reviewsCount: 37,
    badge: "Cozy Fit",
    image: "https://static.wixstatic.com/media/290a69_bf31f9398c5e407d8ea6f7f97391801c~mv2.jpeg",
    description: "Plush brushed fleece interior crewneck sweatshirt. Thoughtful mood typography across the chest, ribbed hem and cuffs with relaxed tailored drop-shoulders.",
    seoKeywords: ["sweatshirt for girls", "couple sweatshirts", "streetwear hoodies"],
    colors: ["#4a4740", "#d1c7bd", "#223127"],
    colorNames: ["Mocha Brown", "Oatmeal Heather", "Forest Moss"],
    sizes: ["S", "M", "L", "XL", "XXL"]
  },
  {
    id: "prod-12",
    slug: "its-not-that-serious-tee",
    name: "Its NOT That Serious Tee",
    category: "t-shirts",
    categoryLabel: "T-Shirts",
    price: 699,
    originalPrice: 899,
    rating: 4.8,
    reviewsCount: 56,
    badge: "Staff Pick",
    image: "https://static.wixstatic.com/media/290a69_0e13d00466364e9089c63dc1d4e5bae9~mv2.jpg",
    description: "A reminder for the over-scheduled mind. Printed on super-soft bio-washed 220 GSM combed cotton that retains shape and drape all day long.",
    seoKeywords: ["oversized white t shirt", "graphic t shirts india", "oversized t shirt"],
    colors: ["#ffffff", "#18181b", "#8b5cf6"],
    colorNames: ["Chalk White", "Shadow Black", "Electric Lavender"],
    sizes: ["S", "M", "L", "XL"]
  },
  {
    id: "prod-13",
    slug: "let-whoever-think-whatever-oversized-tee",
    name: "Let Whoever Think Whatever Oversized Tee",
    category: "t-shirts",
    categoryLabel: "T-Shirts",
    price: 499,
    originalPrice: 799,
    rating: 4.9,
    reviewsCount: 73,
    badge: "Trending",
    image: "https://static.wixstatic.com/media/290a69_041e082d46ae40a2bde9b5b6dd8192f0~mv2.jpg",
    description: "Unapologetic comfort. Oversized slouchy drape with durable silk-screen typography that never fades or cracks. Ideal for unhurried weekends and airport fits.",
    seoKeywords: ["oversized t shirt women", "oversized white t shirt", "graphic t shirt"],
    colors: ["#f4f1ea", "#222222", "#475569"],
    colorNames: ["Warm Ecru", "Obsidian", "Slate Gray"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"]
  },
  {
    id: "prod-14",
    slug: "life-is-all-about-moments-journal",
    name: "Life Is All About Moments Journal",
    category: "stationery",
    categoryLabel: "Stationery & Planners",
    price: 699,
    originalPrice: 899,
    rating: 5.0,
    reviewsCount: 44,
    badge: "Best Gift",
    image: "https://static.wixstatic.com/media/290a69_91e725d89bc54479b653fd7a894056a1~mv2.png",
    description: "Thread-bound reflective wellness journal with 192 numbered archival pages, ribbon bookmark, expandable inner pocket, and gold foil embossed title.",
    seoKeywords: ["daily planner diary", "daily planner 2026", "aesthetic desk setup"],
    colors: ["#2d3748", "#d69e2e", "#702459"],
    colorNames: ["Midnight Navy", "Warm Ochre", "Mulberry"],
    sizes: ["A5 Hardcover (5.8 x 8.3 in)"]
  },
  {
    id: "prod-15",
    slug: "minimal-to-do-list-desk-pad",
    name: "Minimal To-Do List Desk Pad",
    category: "stationery",
    categoryLabel: "Stationery & Planners",
    price: 299,
    originalPrice: 449,
    rating: 4.7,
    reviewsCount: 51,
    badge: "Productivity",
    image: "https://static.wixstatic.com/media/290a69_01488cc71f8644b9b7afea454bae9077~mv2.png",
    description: "Clean landscape layout planner engineered with priority quadrant, habit tracker, and hourly time-blocking section for maximum daily focus.",
    seoKeywords: ["daily planner diary", "to do list", "planner diary"],
    colors: ["#f7fafc", "#edf2f7"],
    colorNames: ["Pure White Pad", "Stone Grey"],
    sizes: ["60 Tear-Off Pages (8.5x5.5 in)"]
  },
  {
    id: "prod-16",
    slug: "mix-match-graphic-phone-case",
    name: "Mix & Match Graphic Phone Case",
    category: "accessories",
    categoryLabel: "Phone Cases & Accessories",
    price: 449,
    originalPrice: 599,
    rating: 4.8,
    reviewsCount: 38,
    badge: "Playful",
    image: "https://static.wixstatic.com/media/290a69_582f447f76424b7b966fda41e87ebfa8~mv2.png",
    description: "Eclectic collage print inspired by modern art and scrapbook memories. Shock-absorbing TPU bumpers with wireless charging compatibility.",
    seoKeywords: ["aesthetic phone cases", "silicone phone case", "cute phone cases"],
    colors: ["#ffffff", "#fef3c7"],
    colorNames: ["Gloss Collage", "Cream Collage"],
    sizes: ["iPhone 12-16 Series"]
  },
  {
    id: "prod-17",
    slug: "oversized-intense-t-shirt",
    name: "Oversized Intense T-Shirt",
    category: "t-shirts",
    categoryLabel: "T-Shirts",
    price: 499,
    originalPrice: 749,
    rating: 4.8,
    reviewsCount: 65,
    badge: "Hot Pick",
    image: "https://static.wixstatic.com/media/290a69_0080f8c30bf84b04a607bebc90bb14a3~mv2.jpeg",
    description: "Heavy cotton streetwear oversized tee with structured neckline and dropped sleeves. Perfect for layering under flannel jackets or over long-sleeve basics.",
    seoKeywords: ["oversized white t shirt", "graphic t shirts india", "oversized t shirt for women"],
    colors: ["#171717", "#f3f0e6", "#52525b"],
    colorNames: ["Ink Black", "Vintage Butter", "Washed Graphite"],
    sizes: ["S", "M", "L", "XL", "XXL"]
  },
  {
    id: "prod-18",
    slug: "pastel-grocery-to-do-list-pads",
    name: "Pastel Grocery & To-Do List Pads",
    category: "stationery",
    categoryLabel: "Stationery & Planners",
    price: 249,
    originalPrice: 349,
    rating: 4.9,
    reviewsCount: 71,
    badge: "Set of 2",
    image: "https://static.wixstatic.com/media/290a69_2ee3bdfb3a0e4370bf3902dea03d0d99~mv2.png",
    description: "Organize market runs and daily reminders in aesthetic harmony. Magnetic back strip securely attaches to refrigerators and metallic memo boards.",
    seoKeywords: ["daily planner diary", "to do list", "planner diary"],
    colors: ["#fce7f3", "#dbeafe"],
    colorNames: ["Pastel Combo", "Mint Lavender"],
    sizes: ["Set of 2 Pads (45 sheets each)"]
  },
  {
    id: "prod-19",
    slug: "personalized-aesthetic-journal",
    name: "Personalized Aesthetic Journal",
    category: "stationery",
    categoryLabel: "Stationery & Planners",
    price: 699,
    originalPrice: 899,
    rating: 5.0,
    reviewsCount: 33,
    badge: "Personalized",
    image: "https://static.wixstatic.com/media/290a69_24343d49d17040f0956a215883481a19~mv2.png",
    description: "Sleek velvet-touch hardcover journal customized with your initials or gold-foil personalized name. 180 pages of fountain-pen-friendly dot-grid paper.",
    seoKeywords: ["daily planner diary", "daily planner 2026", "personalized stationery"],
    colors: ["#1e293b", "#78350f", "#831843"],
    colorNames: ["Sapphire", "Caramel Tan", "Burgundy"],
    sizes: ["Standard A5 (Dot Grid)"]
  },
  {
    id: "prod-20",
    slug: "personalized-leather-journal",
    name: "Personalized Leather Journal",
    category: "stationery",
    categoryLabel: "Stationery & Planners",
    price: 799,
    originalPrice: 1099,
    rating: 4.9,
    reviewsCount: 27,
    badge: "Handcrafted",
    image: "https://static.wixstatic.com/media/290a69_a52896a7d2354fbd809526a5484ddc53~mv2.png",
    description: "Cruelty-free vegan saddle leather cover with wrap-around tie closure and rustic hand-cut edges. Built to age gracefully and become your lifelong creative companion.",
    seoKeywords: ["daily planner diary", "leather journal", "daily planner 2026"],
    colors: ["#713f12", "#27272a", "#365314"],
    colorNames: ["Chestnut Brown", "Jet Noir", "Olive Patina"],
    sizes: ["Refillable A5 Cover + Insert"]
  },
  {
    id: "prod-21",
    slug: "personalized-pink-hat-tote-bag",
    name: "Personalized Pink Hat Tote Bag",
    category: "bags",
    categoryLabel: "Bags & Totes",
    price: 699,
    originalPrice: 899,
    rating: 4.9,
    reviewsCount: 41,
    badge: "Customizable",
    image: "https://static.wixstatic.com/media/290a69_e810bd78a989411e990ae3ab2416c8cc~mv2.jpeg",
    description: "Chic fashion illustration canvas tote featuring personalized typography alongside a playful pink bucket hat motif. Heavy cotton twill with deep interior pocket.",
    seoKeywords: ["canvas tote bag", "office tote bag", "tote bag for women"],
    colors: ["#fdfbf7", "#fce7f3"],
    colorNames: ["Raw Canvas", "Soft Pastel Blush"],
    sizes: ["16 x 15 x 4 in"]
  },
  {
    id: "prod-22",
    slug: "pink-self-care-sticker-phone-case",
    name: "Pink Self-Care Sticker Phone Case",
    category: "accessories",
    categoryLabel: "Phone Cases & Accessories",
    price: 449,
    originalPrice: 599,
    rating: 4.8,
    reviewsCount: 62,
    badge: "Aesthetic",
    image: "https://static.wixstatic.com/media/290a69_6298eeeb625948229a828038657f6d3c~mv2.png",
    description: "Daily self-love reminders and doodle stickers arranged in a stylish collage over a soft powder-pink canvas. Dual-layer military-grade drop defense.",
    seoKeywords: ["aesthetic phone cases", "silicone phone case", "cute phone case"],
    colors: ["#fbcfe8", "#ffffff"],
    colorNames: ["Powder Pink", "Clear Accent"],
    sizes: ["All iPhone & Samsung Models"]
  },
  {
    id: "prod-23",
    slug: "unisex-crew-neck-sweatshirt-gildan-18000",
    name: "Unisex Crew Neck Sweatshirt | Gildan 18000",
    category: "hoodies",
    categoryLabel: "Hoodies & Sweatshirts",
    price: 2944.5,
    originalPrice: 3499,
    rating: 4.9,
    reviewsCount: 95,
    badge: "Heavyweight",
    image: "https://static.wixstatic.com/media/290a69_2ee3bdfb3a0e4370bf3902dea03d0d99~mv2.png",
    description: "Authentic Gildan 18000 heavy blend crewneck. 50% cotton, 50% polyester air-jet spun yarn for reduced pilling and superior pill resistance through all seasons.",
    seoKeywords: ["sweatshirt for girls", "couple sweatshirts", "oversized hoodie men"],
    colors: ["#1c1917", "#e7e5e4", "#1e3a8a", "#064e3b"],
    colorNames: ["Black", "Sport Grey", "Navy", "Dark Green"],
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"]
  },
  {
    id: "prod-24",
    slug: "worthy-collar-sweatshirt",
    name: "Worthy Collar Sweatshirt",
    category: "hoodies",
    categoryLabel: "Hoodies & Sweatshirts",
    price: 1199,
    originalPrice: 1599,
    rating: 4.8,
    reviewsCount: 40,
    badge: "Minimalist",
    image: "https://static.wixstatic.com/media/290a69_fe6e2c356e184c42b6bc00a59d2e4aea~mv2.png",
    description: "Understated collar embroidery reading 'WORTHY'. Clean premium streetwear neckline, relaxed unisex cut, and buttery ultra-soft organic fleece lining.",
    seoKeywords: ["sweatshirt for girls", "couple sweatshirts", "streetwear hoodies"],
    colors: ["#d6d3d1", "#292524", "#78350f"],
    colorNames: ["Stone Grey", "Espresso", "Terracotta"],
    sizes: ["S", "M", "L", "XL"]
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = products;
}
